version: "3.9"
services:
  postgres:
    image: postgres
    restart: always
    container_name: pg
    environment:
      POSTGRES_DB: "skalm"
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "123"
    ports:
      - "5432:5432"

  nats-streaming:  
    image: nats-streaming
    restart: always
    container_name: nats-streaming
    ports:
    - 4222:4222
    - 8222:8222